# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(833, 626)
        Form.setStyleSheet("")
        self.prg = QtWidgets.QProgressBar(Form)
        self.prg.setGeometry(QtCore.QRect(20, 540, 791, 14))
        self.prg.setStyleSheet("")
        self.prg.setProperty("value", 27)
        self.prg.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.prg.setTextVisible(False)
        self.prg.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.prg.setObjectName("prg")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 0, 791, 701))
        self.label.setStyleSheet("image: url(:/splash/test.png);")
        self.label.setText("")
        self.label.setScaledContents(True)
        #self.label.adjustSize(400,400)
        self.label.setObjectName("label")
        self.lab1 = QtWidgets.QLabel(Form)
        self.lab1.setGeometry(QtCore.QRect(30, 510, 141, 30))
        self.lab1.setStyleSheet("color: rgb(45, 205, 25);")
        self.lab1.setObjectName("lab1")
        self.label.raise_()
        self.prg.raise_()
        self.lab1.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lab1.setText(_translate("Form", "正在加载...100%"))
import image
